<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
      <ProjectReference Include="..\Gts\Gts.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="JsonPointer.Net" Version="7.0.2" />
      <PackageReference Include="JsonSchema.Net" Version="9.4.0" />
    </ItemGroup>

</Project>
