<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>Gts.Server</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Gts.Application\Gts.Application.csproj" />
    <ProjectReference Include="..\Gts.Store\Gts.Store.csproj" />
  </ItemGroup>

</Project>
